(6-2)従業員曖昧検索の機能を追加しました.
saia-i/ex-emp-management-bugfix pull request #12
Opened 2022-11-21 01:32 UTC by saia-i

改修要望(6-2)について改修を行いましたので、ご確認をお願いいたします。

2022-11-21 04:47 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-11-21 04:47 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/EmployeeController.java
> +	}
今後のページング処理をシンプルにするために、Controllerにおいて一覧表示を行うshowListメソッドと、曖昧検索を行うメソッドを統合しましょう。

2022-11-21 05:13 UTC, saia-i commented
ご指摘の点に関して修正を行いましたので、ご確認をお願いいたします。

2022-11-21 06:02 UTC, saia-i commented
「指定した文字列が存在しなかった場合」の機能を失念していた為、追加しました。
ご確認をお願いいたします。

2022-11-22 06:51 UTC, igamasayuki approved these changes
承認いたします。
気になる点をコメントしました。

承認しますが、必要であれば新たにブランチを切って修正をしておきましょう。

2022-11-22 06:51 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/EmployeeController.java
>  		return "employee/list";
もう少しシンプルになります。
答えとなってしまいますが、以下のような形で修正しましょう。
メソッド名や変数名は適宜読み替えてください。

Controller
```
public String showList(String searchName, Model model) {

  List employees = employeeService.showListByName(searchName);

  if(employees.isEmpty()) {
    model.addAttribute("searchError", "１件もありませんでした");
    employees = employeeService.showList();
  }
  model.addAttribute("employeeList", employees);
  return "employee/list";
}
```

2022-11-22 06:52 UTC, merged