(5-3)パスワードハッシュ化の機能を追加しました.
saia-i/ex-emp-management-bugfix pull request #13
Opened 2022-11-21 03:09 UTC by saia-i

改修要望(5-3)について修正をしましたので、ご確認をお願いいたします。

2022-11-21 04:53 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-11-21 04:53 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/service/AdministratorService.java
> +		Administrator administrator = administratorRepository.findByMailAddressAndPassward(mailAddress);
AdministratorRepositoryにはfindByMailAddress()があるため、それを利用してください。

2022-11-21 04:53 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/repository/AdministratorRepository.java
> +	public Administrator findByMailAddressAndPassward(String mailAddress) {
ここを修正するのではなく、AdministratorRepositoryにはfindByMailAddress()があるため、それを利用してください。

2022-11-21 05:31 UTC, saia-i commented
ご指摘の点に関して修正を行いましたので、ご確認をお願いいたします。

2022-11-22 06:54 UTC, igamasayuki approved these changes
承認いたします。
気になる点をコメントしました。
承認しますが次回以降意識していただければと思います。

2022-11-22 06:54 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/service/AdministratorService.java
> +			if(passwordCheck==false) {
`if(!passwordCheck) {`

が良く書かれるやり方です。次回からで良いので意識すると良いと思います。

2022-11-22 06:54 UTC, merged