(1-3)Eメール重複チェックの機能を追加しました.
saia-i/ex-emp-management-bugfix pull request #6
Opened 2022-11-18 05:28 UTC by saia-i

改修依頼(1-3)について改修を行いましたので、ご確認をお願いいたします。

2022-11-18 07:49 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-11-18 07:49 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +				model.addAttribute("duplicationError", "既に登録されているメールアドレスです");
　今回のエラーメッセージの登録ですが、
　model.addAttribute("キー", "エラーメッセージ");
　ではなく、resultにエラーメッセージを追加することができます。
　このようにすると、viewでは
　「○○を入力してください」
　というformのvalidateエラーが出る箇所に、今回のものと共通でエラーメッセージを出すことができます。
　BindingResultのAPIマニュアルを見ながら探してみてください。

2022-11-18 08:50 UTC, saia-i commented
ご指摘の点に関して修正を行いましたので、ご確認をお願いいたします。

2022-11-18 10:18 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-11-18 10:18 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
>  			}
この処理は、
if(result.hasErrors()){
・・・
}
の上に書きましょう。

2022-11-19 09:52 UTC, saia-i commented
ご指摘の点に関して修正を行いましたので、ご確認をお願いいたします。

2022-11-19 19:39 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-11-19 19:39 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +			return "administrator/insert";
とてもよくなりました。
この83行目は消して問題ありません。(理由はおそらく理解できると思いますが、わからなければご質問ください。)
`return "administrator/insert";`

消して再度push＆再レビュー依頼をお願いします。

2022-11-20 23:58 UTC, saia-i commented
修正を行いましたので、ご確認をお願いいたします。

2022-11-21 04:42 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2022-11-21 04:42 UTC, merged