(1-5)確認用パスワードの欄を追加しました.
saia-i/ex-emp-management-bugfix pull request #7
Opened 2022-11-18 06:16 UTC by saia-i

改修依頼(1-5)について改修を行いましたので、ご確認をお願いいたします。

2022-11-18 07:51 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-11-18 07:51 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +			System.out.println(form.getConfirmPassword());
pushする際はデバッグ用のsysoutは消すようにお願いします。

2022-11-18 07:51 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +			model.addAttribute("confirmError", "パスワードが一致していません");
　今回のエラーメッセージの登録ですが、
　model.addAttribute("キー", "エラーメッセージ");
　ではなく、resultにエラーメッセージを追加することができます。
　このようにすると、viewでは
　「○○を入力してください」
　というformのvalidateエラーが出る箇所に、今回のものと共通でエラーメッセージを出すことができます。
　BindingResultのAPIマニュアルを見ながら探してみてください。

2022-11-19 09:42 UTC, saia-i commented
ご指摘を頂きました点について修正を行いましたので、ご確認をお願いいたします。

2022-11-19 19:40 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-11-19 19:40 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
>  			return "administrator/insert";
とてもよくなりました。
この81行目は消して問題ありません。(理由はおそらく理解できると思いますが、わからなければご質問ください。)
return "administrator/insert";

消して再度push＆再レビュー依頼をお願いします。

2022-11-21 01:06 UTC, saia-i commented
該当行の削除を行いましたので、ご確認よろしくお願いいたします。

2022-11-21 04:44 UTC, igamasayuki approved these changes
承認いたします。
気になる点をコメントしました。
承認しますが、必要であれば新たにブランチを切って修正をしておきましょう。

2022-11-21 04:44 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +	public String insert(@Validated InsertAdministratorForm form,BindingResult result,Model model) {
ここの
`,Model model`
は不要な気がします。

必要だったらすみません。

2022-11-21 04:45 UTC, merged